### ISSUE TITLE
Telescope path not read from config file

### ISSUE THREAD

**Issue by MikeBurke-RL** [GeneaLabs/nova-telescope#2]
The telescope path is hard coded to '/telescope' instead of reading the telescope.path config variable.

**Comment by mikebronner** [comment]
@MikeBurke-RL Thanks! I'll get that fixed ASAP. :)

**Comment by mikebronner** [comment]
@MikeBurke-RL Give release 0.1.1 a try and let me know how it works for you. Thanks again :) I'll be making the same update for the Horizon package.
