### ISSUE TITLE
why only works on laravel 6.x??

### ISSUE THREAD

**Issue by nachete1987** [GeneaLabs/nova-telescope#5]
In composer.json, laravel 6.x is minimum version, why? I have 5.8 version and can't install this package.

Thanks a lot.

**Comment by mikebronner** [comment]
Hi @nachete1987 ,

As a general rule, I don't maintain backward compatibility to legacy versions of Laravel. Feel free to fork and make adjustments as you need.

There are several reasons not to keep apps at old Laravel versions, including the problems associated with not keeping your Laravel app up-to-date, increased maintenance costs, etc.
